# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e52016e53536cedb05ff579492a7f8117339aad95c15e6686756d4b8d257e8e6a55e575c731b06a81bbd8e8f110ec9c9d37aa2689db13f27aee2303cec9c087

test:
  secret_key_base: cee7f8807f200fd8970df33a4c85b09f73c530b607c5ebf6907117416a0e7ced8f7eed5e9869a981e12b2fff574a2e9e1cbada01315619e272130e390e85b256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
